### ISSUE TITLE
custom lyrics 

### ISSUE THREAD

**Issue by katywilliams1121** [flowese/UdioWrapper#1]
please add a feature for the custom lyrics input and other extend feature (if possible)

**Comment by flowese** [comment]
Hello @katywilliams1121,

Thank you for your suggestion regarding custom lyrics input and extension features. I am pleased to inform you that we have updated the README and released a new version of the UdioWrapper that now comprehensively includes these features, including enhanced capabilities for handling custom lyrics.

Please make sure to update the library to the latest version to access these new functionalities and improvements. 

You can do this by running:

```python
pip install --upgrade --no-cache-dir udio_wrapper

```

You will find detailed examples of how to use the custom lyrics input for the initial song, extensions, and outros in the updated README. These examples should provide you with clear guidance on how to tailor the song generation process to your specific needs.

We appreciate your feedback and hope that the new functionalities and improvements meet your expectations.

Best regards,
