### ISSUE TITLE
Issue in first request 

### ISSUE THREAD

**Issue by katywilliams1121** [flowese/UdioWrapper#2]
![Screenshot_2024-04-14-00-08-52-935_com android chrome](https://github.com/flowese/UdioWrapper/assets/151863894/d9de7f96-3fb6-4a99-9d8b-4235a063b542)
![Screenshot_2024-04-14-00-08-56-997_com android chrome](https://github.com/flowese/UdioWrapper/assets/151863894/97b7bd61-75ce-4de5-89be-f0b408bcd6e2)
i am getting this error when running first request (it's successfull because i know if i do another one when the first one is running i will get 429 error on the second request) 

but why this is happening

**Comment by flowese** [comment]
Hello @katywilliams1121,

Thank you for reporting this issue with the requests in UdioWrapper. 
I noticed you mentioned a 429 error, which typically indicates a "Too Many Requests" error.

To assist you better, could you clarify if the error occurs when trying to extend a song?
Additionally, Udio has been quite saturated at certain times of the day over the past few days,
which might be related to this issue.

Could you please describe in more detail what type of request you are making when you encounter this error?

We look forward to your response to better assist you.

**Comment by katywilliams1121** [comment]
i would like to talk in brief 

my discord:-  the_r0ktim
telegram:- @MISTERofMadness

would be kind of you if you help me set this up in my bot
