### ISSUE TITLE
ability to get both gens

### ISSUE THREAD

**Issue by Questscape** [flowese/UdioWrapper#3]
there is 2 gens for each prompt, but this api seems to only give one of them. Can you add the ability to get both?

**Comment by katywilliams1121** [comment]
it depends on udio, they are recently giving 1 song per generation

**Comment by flowese** [comment]
Great news! We are finalizing adjustments to the library, including adapting to recent changes Udio has made to the API, such as call parameters and header issues. Additionally, we are working to enable you to download all the generations that Udio returns, currently 2 per generation. The new version 0.0.3 is very likely to be available later today. I'll let you know as soon as you can start using it. Thanks for your patience and for staying tuned for updates!

**Comment by flowese** [comment]
We have just released version 0.0.3 of the UdioWrapper library, which includes the ability to download all the generations that Udio returns, currently 2 per generation. We have also adapted the library to the recent changes Udio has made to the API, such as call parameters and header issues. The new version is now available, so you can start using it. Thanks for your patience and for staying tuned for the updates!
