### ISSUE TITLE
Whats the point of this?

### ISSUE THREAD

**Issue by mcdthekid** [flowese/UdioWrapper#4]
I understand that this is a reverse-engineered process to use Udio locally, but what's the point? Before they took down manual model you could use custom models against there tos such as juice wrld. Now that its gone you cant, is this suppose to let you bypass that and use whatever prompt you want without a moderator banning your request or is this only for using udio locally?
<br/>
<hr/>

<details><summary>This repo is using Opire - what does it means? 👇</summary><br/>💸Everyone can add rewards for this issue commenting <code>/reward 100</code> (replace <code>100</code> with the amount)<br/>💪 If someone starts working on this issue to earn the rewards, they can comment <code>/try</code> to let everyone know!<br/>🙌 And when they open the PR, they can comment <code>/claim #4</code> either in the PR description or in a PR's comment<br/><br/>👀 Also, everyone can tip any user commenting <code>/tip 20 @mcdthekid</code> (replace <code>20</code> with the amount, and <code>@mcdthekid</code> with the user to tip)<br/><br/>If you want to learn more, go to our <a href="https://docs.opire.dev">documentation</a></details>

**Comment by flowese** [comment]
I’m not entirely sure I understand your point. Are you really raising an issue for this? The purpose of this library is for research use and it’s not intended to circumvent Udio’s regulations. As described in the README file, this package allows you to run Udio in the same way as it would be online but locally, which is useful, for example, to integrate it into your personal projects. I hope this clears things up, and please, I ask you not to open an issue just to make inquiries.
