### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by su161021** [flowese/UdioWrapper#6]
How do you solve the problem !
TypeError: 'module' object is not callable
<br/>
<hr/>

<details><summary>This repo is using Opire - what does it means? 👇</summary><br/>💸Everyone can add rewards for this issue commenting <code>/reward 100</code> (replace <code>100</code> with the amount)<br/>💪 If someone starts working on this issue to earn the rewards, they can comment <code>/try</code> to let everyone know!<br/>🙌 And when they open the PR, they can comment <code>/claim #6</code> either in the PR description or in a PR's comment<br/><br/>👀 Also, everyone can tip any user commenting <code>/tip 20 @su161021</code> (replace <code>20</code> with the amount, and <code>@su161021</code> with the user to tip)<br/><br/>If you want to learn more, go to our <a href="https://docs.opire.dev">documentation</a></details>

**Comment by flowese** [comment]
issue moved to: https://github.com/flowese/UdioWrapper/issues/7

**Comment by mudabbrify** [comment]
What's the solution to this error?
