### ISSUE TITLE
How to force no lyrics?

### ISSUE THREAD

**Issue by romastra** [flowese/UdioWrapper#8]
Tried to use None and "" as lyrics, as actually not incluting property in dict. All variants produces text from time to time.

Adding "instrumental" into prompt doesn't help since being associated with orchestral instruments. Seems the word "no" is not getting into the account at all.

Same prompt on web site makes tracks with no lyrics with ease.

**Comment by romastra** [comment]
Actually, the problem is solved in generate_song(). lyricInput was set to None if "" detected.

**Comment by 57875t** [comment]
I don't know what that  mean and  your tips  how forced  no  lyrics,can  you explain this?

**Comment by 57875t** [comment]
Sorry  became lm
 From china  your  say  some  world  l don't understand  sorry  about that
